name: handleliste
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.13.1
  share: ^2.0.4
  easy_dynamic_theme: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/avocado.png"