// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTQyC89diWYFfFzUp_KigNVqVEdYyByU',
    appId: '1:711997283963:web:43730e65f75186adcb8cde',
    messagingSenderId: '711997283963',
    projectId: 'handlelisteflutter',
    authDomain: 'handlelisteflutter.firebaseapp.com',
    databaseURL: 'https://handlelisteflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'handlelisteflutter.appspot.com',
    measurementId: 'G-C8GTF8Y0WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwiEefcNF9orMb7ni1C2tgzcBuVSpcZE',
    appId: '1:711997283963:android:a255519d6e316cc0cb8cde',
    messagingSenderId: '711997283963',
    projectId: 'handlelisteflutter',
    databaseURL: 'https://handlelisteflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'handlelisteflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfDmpucwhJ_KMuFQfx2mMGf9unw0RZQM',
    appId: '1:711997283963:ios:515a6b4f075ba634cb8cde',
    messagingSenderId: '711997283963',
    projectId: 'handlelisteflutter',
    databaseURL: 'https://handlelisteflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'handlelisteflutter.appspot.com',
    iosBundleId: 'com.example.handleliste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMfDmpucwhJ_KMuFQfx2mMGf9unw0RZQM',
    appId: '1:711997283963:ios:4dd0df0a8b821ac9cb8cde',
    messagingSenderId: '711997283963',
    projectId: 'handlelisteflutter',
    databaseURL: 'https://handlelisteflutter-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'handlelisteflutter.appspot.com',
    iosBundleId: 'com.example.handleliste.RunnerTests',
  );
}
